# ═══════════════════════════════════════════════════════════════
#  🔥 Meru Cozy — Hyprpaper Config
# ═══════════════════════════════════════════════════════════════

preload = ~/.config/hypr/wallpaper.png

wallpaper {
    monitor =
    path = ~/.config/hypr/wallpaper.png
    fit_mode = cover
}

splash = false
ipc = true
