-- ═══════════════════════════════════════════════════════════════
--  🔥 Meru Cozy — Neovim Colorscheme
--  Succubus vibes: deep crimson, warm amber, fairy light glow
-- ═══════════════════════════════════════════════════════════════

local M = {}

M.palette = {
  bg_dark    = "#1a0e10",
  bg         = "#211316",
  bg_light   = "#2b1518",
  surface    = "#3d1e22",
  overlay    = "#4a2428",
  muted      = "#5a3a30",
  subtle     = "#6e5040",
  fg_dim     = "#a89080",
  fg         = "#e8dcd0",
  red        = "#843727",
  red_bright = "#c53a3a",
  magenta    = "#8b2e2e",
  mag_bright = "#b84545",
  amber      = "#c56d3a",
  gold       = "#e8a04a",
  teal       = "#0b596c",
  teal_br    = "#1a7a8a",
  blue       = "#1e3a5c",
  blue_br    = "#3c608b",
  cyan       = "#7c94bc",
  cyan_br    = "#a0b4d0",
  none       = "NONE",
}

local function hi(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

function M.load()
  if vim.g.colors_name then
    vim.cmd("hi clear")
  end
  vim.o.termguicolors = true
  vim.g.colors_name = "meru-cozy"

  local p = M.palette

  -- ── Editor ────────────────────────────────────────────────
  hi("Normal",         { fg = p.fg, bg = p.bg_dark })
  hi("NormalNC",       { fg = p.fg, bg = p.bg_dark })
  hi("NormalFloat",    { fg = p.fg, bg = p.bg_light })
  hi("NormalSB",       { fg = p.fg_dim, bg = p.bg })
  hi("Cursor",         { fg = p.bg_dark, bg = p.amber })
  hi("lCursor",        { fg = p.bg_dark, bg = p.amber })
  hi("CursorLine",     { bg = p.bg })
  hi("CursorColumn",   { bg = p.bg })
  hi("ColorColumn",    { bg = p.bg })
  hi("Conceal",        { fg = p.muted })
  hi("Directory",      { fg = p.teal, bold = true })
  hi("EndOfBuffer",    { fg = p.bg_dark })
  hi("ErrorMsg",       { fg = p.red_bright, bold = true })
  hi("WarningMsg",     { fg = p.gold, bold = true })
  hi("MoreMsg",        { fg = p.teal })
  hi("ModeMsg",        { fg = p.amber, bold = true })
  hi("MsgArea",        { fg = p.fg_dim })
  hi("MsgSeparator",   { fg = p.overlay, bg = p.bg_dark })
  hi("Folded",         { fg = p.subtle, bg = p.bg })
  hi("FoldColumn",     { fg = p.muted, bg = p.bg_dark })
  hi("SignColumn",     { fg = p.muted, bg = p.bg_dark })
  hi("IncSearch",      { fg = p.bg_dark, bg = p.gold, bold = true })
  hi("CurSearch",      { fg = p.bg_dark, bg = p.gold, bold = true })
  hi("Search",         { fg = p.bg_dark, bg = p.amber })
  hi("Substitute",     { fg = p.bg_dark, bg = p.red_bright })
  hi("LineNr",         { fg = p.muted })
  hi("CursorLineNr",   { fg = p.amber, bold = true })
  hi("MatchParen",     { fg = p.gold, bg = p.overlay, bold = true })
  hi("NonText",        { fg = p.muted })
  hi("SpecialKey",     { fg = p.muted })
  hi("Pmenu",          { fg = p.fg, bg = p.bg_light })
  hi("PmenuSel",       { fg = p.gold, bg = p.overlay, bold = true })
  hi("PmenuSbar",      { bg = p.surface })
  hi("PmenuThumb",     { bg = p.amber })
  hi("Question",       { fg = p.teal })
  hi("QuickFixLine",   { bg = p.overlay })
  hi("SpellBad",       { undercurl = true, sp = p.red_bright })
  hi("SpellCap",       { undercurl = true, sp = p.gold })
  hi("SpellLocal",     { undercurl = true, sp = p.teal })
  hi("SpellRare",      { undercurl = true, sp = p.cyan })
  hi("StatusLine",     { fg = p.fg, bg = p.bg_light })
  hi("StatusLineNC",   { fg = p.muted, bg = p.bg })
  hi("TabLine",        { fg = p.fg_dim, bg = p.bg })
  hi("TabLineFill",    { bg = p.bg_dark })
  hi("TabLineSel",     { fg = p.fg, bg = p.overlay, bold = true })
  hi("Title",          { fg = p.gold, bold = true })
  hi("Visual",         { bg = p.overlay })
  hi("VisualNOS",      { bg = p.overlay })
  hi("Whitespace",     { fg = p.muted })
  hi("WildMenu",       { fg = p.gold, bg = p.overlay })
  hi("WinBar",         { fg = p.fg_dim, bg = p.bg_dark })
  hi("WinBarNC",       { fg = p.muted, bg = p.bg_dark })
  hi("WinSeparator",   { fg = p.overlay })
  hi("FloatBorder",    { fg = p.amber, bg = p.bg_light })
  hi("FloatTitle",     { fg = p.gold, bg = p.bg_light, bold = true })

  -- ── Diff ──────────────────────────────────────────────────
  hi("DiffAdd",        { bg = "#0b2d1a" })
  hi("DiffChange",     { bg = "#2b2010" })
  hi("DiffDelete",     { bg = "#2d0e12" })
  hi("DiffText",       { bg = "#3d2a10" })

  -- ── Syntax ────────────────────────────────────────────────
  hi("Comment",        { fg = p.subtle, italic = true })
  hi("Constant",       { fg = p.gold })
  hi("String",         { fg = p.teal })
  hi("Character",      { fg = p.teal_br })
  hi("Number",         { fg = p.gold })
  hi("Boolean",        { fg = p.red_bright, bold = true })
  hi("Float",          { fg = p.gold })
  hi("Identifier",     { fg = p.fg })
  hi("Function",       { fg = p.amber, bold = true })
  hi("Statement",      { fg = p.red })
  hi("Conditional",    { fg = p.red, italic = true })
  hi("Repeat",         { fg = p.red, italic = true })
  hi("Label",          { fg = p.amber })
  hi("Operator",       { fg = p.fg_dim })
  hi("Keyword",        { fg = p.red_bright, italic = true })
  hi("Exception",      { fg = p.mag_bright })
  hi("PreProc",        { fg = p.mag_bright })
  hi("Include",        { fg = p.mag_bright, italic = true })
  hi("Define",         { fg = p.mag_bright })
  hi("Macro",          { fg = p.mag_bright, bold = true })
  hi("PreCondit",      { fg = p.mag_bright })
  hi("Type",           { fg = p.mag_bright })
  hi("StorageClass",   { fg = p.red })
  hi("Structure",      { fg = p.mag_bright })
  hi("Typedef",        { fg = p.mag_bright })
  hi("Special",        { fg = p.amber })
  hi("SpecialChar",    { fg = p.gold })
  hi("Tag",            { fg = p.amber })
  hi("Delimiter",      { fg = p.fg_dim })
  hi("SpecialComment", { fg = p.amber, italic = true })
  hi("Debug",          { fg = p.red_bright })
  hi("Underlined",     { underline = true, fg = p.teal })
  hi("Ignore",         { fg = p.muted })
  hi("Error",          { fg = p.red_bright, bold = true })
  hi("Todo",           { fg = p.bg_dark, bg = p.gold, bold = true })

  -- ── Treesitter ────────────────────────────────────────────
  hi("@variable",               { fg = p.fg })
  hi("@variable.builtin",       { fg = p.mag_bright, italic = true })
  hi("@variable.parameter",     { fg = p.cyan_br })
  hi("@variable.member",        { fg = p.cyan })
  hi("@constant",               { fg = p.gold })
  hi("@constant.builtin",       { fg = p.gold, bold = true })
  hi("@constant.macro",         { fg = p.gold })
  hi("@module",                 { fg = p.mag_bright })
  hi("@module.builtin",         { fg = p.mag_bright, italic = true })
  hi("@label",                  { fg = p.amber })
  hi("@string",                 { fg = p.teal })
  hi("@string.documentation",   { fg = p.teal_br, italic = true })
  hi("@string.regex",           { fg = p.teal_br })
  hi("@string.escape",          { fg = p.gold })
  hi("@string.special",         { fg = p.teal_br })
  hi("@character",              { fg = p.teal_br })
  hi("@character.special",      { fg = p.gold })
  hi("@boolean",                { fg = p.red_bright, bold = true })
  hi("@number",                 { fg = p.gold })
  hi("@number.float",           { fg = p.gold })
  hi("@type",                   { fg = p.mag_bright })
  hi("@type.builtin",           { fg = p.mag_bright, italic = true })
  hi("@type.definition",        { fg = p.mag_bright })
  hi("@attribute",              { fg = p.amber })
  hi("@attribute.builtin",      { fg = p.amber, italic = true })
  hi("@property",               { fg = p.cyan })
  hi("@function",               { fg = p.amber, bold = true })
  hi("@function.builtin",       { fg = p.amber })
  hi("@function.call",          { fg = p.amber })
  hi("@function.macro",         { fg = p.gold })
  hi("@function.method",        { fg = p.amber })
  hi("@function.method.call",   { fg = p.amber })
  hi("@constructor",            { fg = p.mag_bright })
  hi("@operator",               { fg = p.fg_dim })
  hi("@keyword",                { fg = p.red_bright, italic = true })
  hi("@keyword.coroutine",      { fg = p.red, italic = true })
  hi("@keyword.function",       { fg = p.red, italic = true })
  hi("@keyword.operator",       { fg = p.fg_dim })
  hi("@keyword.import",         { fg = p.mag_bright, italic = true })
  hi("@keyword.type",           { fg = p.red })
  hi("@keyword.modifier",       { fg = p.red, italic = true })
  hi("@keyword.repeat",         { fg = p.red, italic = true })
  hi("@keyword.return",         { fg = p.red_bright, italic = true })
  hi("@keyword.debug",          { fg = p.red_bright })
  hi("@keyword.exception",      { fg = p.mag_bright })
  hi("@keyword.conditional",    { fg = p.red, italic = true })
  hi("@punctuation.delimiter",  { fg = p.fg_dim })
  hi("@punctuation.bracket",    { fg = p.fg_dim })
  hi("@punctuation.special",    { fg = p.amber })
  hi("@comment",                { fg = p.subtle, italic = true })
  hi("@comment.documentation",  { fg = p.subtle, italic = true })
  hi("@comment.error",          { fg = p.red_bright, bold = true })
  hi("@comment.warning",        { fg = p.gold, bold = true })
  hi("@comment.note",           { fg = p.teal, bold = true })
  hi("@comment.todo",           { fg = p.bg_dark, bg = p.gold, bold = true })
  hi("@markup.heading",         { fg = p.gold, bold = true })
  hi("@markup.heading.1",       { fg = p.gold, bold = true })
  hi("@markup.heading.2",       { fg = p.amber, bold = true })
  hi("@markup.heading.3",       { fg = p.mag_bright, bold = true })
  hi("@markup.italic",          { italic = true })
  hi("@markup.strong",          { bold = true })
  hi("@markup.strikethrough",   { strikethrough = true })
  hi("@markup.underline",       { underline = true })
  hi("@markup.link",            { fg = p.teal, underline = true })
  hi("@markup.link.url",        { fg = p.teal, underline = true })
  hi("@markup.raw",             { fg = p.teal_br })
  hi("@markup.list",            { fg = p.amber })
  hi("@tag",                    { fg = p.red_bright })
  hi("@tag.attribute",          { fg = p.amber, italic = true })
  hi("@tag.delimiter",          { fg = p.fg_dim })
  hi("@diff.plus",              { fg = p.teal })
  hi("@diff.minus",             { fg = p.red_bright })
  hi("@diff.delta",             { fg = p.amber })

  -- ── LSP Semantic Tokens ───────────────────────────────────
  hi("@lsp.type.boolean",       { link = "@boolean" })
  hi("@lsp.type.builtinType",   { link = "@type.builtin" })
  hi("@lsp.type.comment",       { link = "@comment" })
  hi("@lsp.type.decorator",     { link = "@attribute" })
  hi("@lsp.type.enum",          { link = "@type" })
  hi("@lsp.type.enumMember",    { link = "@constant" })
  hi("@lsp.type.function",      { link = "@function" })
  hi("@lsp.type.interface",     { fg = p.mag_bright, italic = true })
  hi("@lsp.type.keyword",       { link = "@keyword" })
  hi("@lsp.type.macro",         { link = "@function.macro" })
  hi("@lsp.type.method",        { link = "@function.method" })
  hi("@lsp.type.namespace",     { link = "@module" })
  hi("@lsp.type.number",        { link = "@number" })
  hi("@lsp.type.operator",      { link = "@operator" })
  hi("@lsp.type.parameter",     { link = "@variable.parameter" })
  hi("@lsp.type.property",      { link = "@property" })
  hi("@lsp.type.string",        { link = "@string" })
  hi("@lsp.type.struct",        { link = "@type" })
  hi("@lsp.type.type",          { link = "@type" })
  hi("@lsp.type.typeParameter",  { fg = p.mag_bright })
  hi("@lsp.type.variable",      { link = "@variable" })

  -- ── Diagnostics ───────────────────────────────────────────
  hi("DiagnosticError",          { fg = p.red_bright })
  hi("DiagnosticWarn",           { fg = p.gold })
  hi("DiagnosticInfo",           { fg = p.teal })
  hi("DiagnosticHint",           { fg = p.cyan })
  hi("DiagnosticOk",             { fg = p.teal_br })
  hi("DiagnosticVirtualTextError", { fg = p.red_bright, bg = "#2d0e12" })
  hi("DiagnosticVirtualTextWarn",  { fg = p.gold, bg = "#2b2010" })
  hi("DiagnosticVirtualTextInfo",  { fg = p.teal, bg = "#0a1a20" })
  hi("DiagnosticVirtualTextHint",  { fg = p.cyan, bg = "#151a24" })
  hi("DiagnosticUnderlineError", { undercurl = true, sp = p.red_bright })
  hi("DiagnosticUnderlineWarn",  { undercurl = true, sp = p.gold })
  hi("DiagnosticUnderlineInfo",  { undercurl = true, sp = p.teal })
  hi("DiagnosticUnderlineHint",  { undercurl = true, sp = p.cyan })

  -- ── Git Signs ─────────────────────────────────────────────
  hi("GitSignsAdd",              { fg = p.teal })
  hi("GitSignsChange",           { fg = p.amber })
  hi("GitSignsDelete",           { fg = p.red_bright })
  hi("GitSignsAddNr",            { fg = p.teal })
  hi("GitSignsChangeNr",         { fg = p.amber })
  hi("GitSignsDeleteNr",         { fg = p.red_bright })
  hi("GitSignsAddLn",            { bg = "#0b2d1a" })
  hi("GitSignsChangeLn",         { bg = "#2b2010" })
  hi("GitSignsDeleteLn",         { bg = "#2d0e12" })

  -- ── Telescope ─────────────────────────────────────────────
  hi("TelescopeNormal",         { fg = p.fg, bg = p.bg })
  hi("TelescopeBorder",         { fg = p.overlay, bg = p.bg })
  hi("TelescopeTitle",          { fg = p.gold, bg = p.bg, bold = true })
  hi("TelescopePromptNormal",   { fg = p.fg, bg = p.bg_light })
  hi("TelescopePromptBorder",   { fg = p.amber, bg = p.bg_light })
  hi("TelescopePromptTitle",    { fg = p.bg_dark, bg = p.amber, bold = true })
  hi("TelescopePromptPrefix",   { fg = p.amber, bg = p.bg_light })
  hi("TelescopeResultsNormal",  { fg = p.fg, bg = p.bg })
  hi("TelescopeResultsBorder",  { fg = p.overlay, bg = p.bg })
  hi("TelescopePreviewNormal",  { fg = p.fg, bg = p.bg_dark })
  hi("TelescopePreviewBorder",  { fg = p.overlay, bg = p.bg_dark })
  hi("TelescopePreviewTitle",   { fg = p.bg_dark, bg = p.teal, bold = true })
  hi("TelescopeSelection",     { fg = p.gold, bg = p.overlay })
  hi("TelescopeSelectionCaret", { fg = p.amber })
  hi("TelescopeMatching",      { fg = p.gold, bold = true })

  -- ── Neo-tree ──────────────────────────────────────────────
  hi("NeoTreeNormal",           { fg = p.fg, bg = p.bg })
  hi("NeoTreeNormalNC",         { fg = p.fg, bg = p.bg })
  hi("NeoTreeRootName",         { fg = p.amber, bold = true })
  hi("NeoTreeDirectoryName",    { fg = p.fg })
  hi("NeoTreeDirectoryIcon",    { fg = p.amber })
  hi("NeoTreeFileName",         { fg = p.fg })
  hi("NeoTreeFileIcon",         { fg = p.fg_dim })
  hi("NeoTreeGitAdded",         { fg = p.teal })
  hi("NeoTreeGitModified",      { fg = p.amber })
  hi("NeoTreeGitDeleted",       { fg = p.red_bright })
  hi("NeoTreeGitUntracked",     { fg = p.gold })
  hi("NeoTreeIndentMarker",     { fg = p.overlay })
  hi("NeoTreeWinSeparator",     { fg = p.bg_dark, bg = p.bg_dark })
  hi("NeoTreeCursorLine",       { bg = p.bg_light })

  -- ── Indent Blankline ──────────────────────────────────────
  hi("IblIndent",               { fg = p.bg_light })
  hi("IblScope",                { fg = p.overlay })
  hi("IndentBlanklineChar",     { fg = p.bg_light })
  hi("IndentBlanklineContextChar", { fg = p.overlay })

  -- ── Which-Key ─────────────────────────────────────────────
  hi("WhichKey",                { fg = p.amber })
  hi("WhichKeyGroup",           { fg = p.mag_bright })
  hi("WhichKeyDesc",            { fg = p.fg })
  hi("WhichKeySeparator",       { fg = p.muted })
  hi("WhichKeyFloat",           { bg = p.bg })
  hi("WhichKeyBorder",          { fg = p.overlay, bg = p.bg })
  hi("WhichKeyValue",           { fg = p.fg_dim })

  -- ── Noice ─────────────────────────────────────────────────
  hi("NoiceCmdline",            { fg = p.fg, bg = p.bg_light })
  hi("NoiceCmdlinePopup",       { fg = p.fg, bg = p.bg_light })
  hi("NoiceCmdlinePopupBorder", { fg = p.amber, bg = p.bg_light })
  hi("NoiceCmdlineIcon",        { fg = p.amber })
  hi("NoiceConfirm",            { fg = p.fg, bg = p.bg_light })
  hi("NoiceConfirmBorder",      { fg = p.amber, bg = p.bg_light })
  hi("NoiceMini",               { fg = p.fg, bg = p.bg_light })

  -- ── Flash ─────────────────────────────────────────────────
  hi("FlashLabel",              { fg = p.bg_dark, bg = p.gold, bold = true })
  hi("FlashMatch",              { fg = p.fg, bg = p.overlay })
  hi("FlashCurrent",            { fg = p.bg_dark, bg = p.amber })
  hi("FlashBackdrop",           { fg = p.muted })

  -- ── Snacks ────────────────────────────────────────────────
  hi("SnacksDashboardHeader",   { fg = p.amber })
  hi("SnacksDashboardFooter",   { fg = p.subtle, italic = true })
  hi("SnacksDashboardIcon",     { fg = p.amber })
  hi("SnacksDashboardKey",      { fg = p.gold, bold = true })
  hi("SnacksDashboardDesc",     { fg = p.fg_dim })
  hi("SnacksDashboardFile",     { fg = p.fg })
  hi("SnacksDashboardDir",      { fg = p.subtle })
  hi("SnacksDashboardSpecial",  { fg = p.mag_bright })
  hi("SnacksDashboardTitle",    { fg = p.gold, bold = true })
  hi("SnacksNotifierInfo",      { fg = p.teal })
  hi("SnacksNotifierWarn",      { fg = p.gold })
  hi("SnacksNotifierError",     { fg = p.red_bright })
  hi("SnacksNotifierDebug",     { fg = p.cyan })
  hi("SnacksIndent",            { fg = p.bg_light })
  hi("SnacksIndentScope",       { fg = p.overlay })

  -- ── nvim-cmp ──────────────────────────────────────────────
  hi("CmpItemAbbr",             { fg = p.fg })
  hi("CmpItemAbbrDeprecated",   { fg = p.muted, strikethrough = true })
  hi("CmpItemAbbrMatch",        { fg = p.gold, bold = true })
  hi("CmpItemAbbrMatchFuzzy",   { fg = p.gold })
  hi("CmpItemMenu",             { fg = p.subtle })
  hi("CmpItemKindDefault",      { fg = p.fg_dim })
  hi("CmpItemKindFunction",     { fg = p.amber })
  hi("CmpItemKindMethod",       { fg = p.amber })
  hi("CmpItemKindVariable",     { fg = p.fg })
  hi("CmpItemKindField",        { fg = p.cyan })
  hi("CmpItemKindProperty",     { fg = p.cyan })
  hi("CmpItemKindClass",        { fg = p.mag_bright })
  hi("CmpItemKindInterface",    { fg = p.mag_bright })
  hi("CmpItemKindStruct",       { fg = p.mag_bright })
  hi("CmpItemKindModule",       { fg = p.mag_bright })
  hi("CmpItemKindKeyword",      { fg = p.red_bright })
  hi("CmpItemKindText",         { fg = p.fg_dim })
  hi("CmpItemKindSnippet",      { fg = p.teal })
  hi("CmpItemKindEnum",         { fg = p.mag_bright })
  hi("CmpItemKindValue",        { fg = p.gold })
  hi("CmpItemKindConstant",     { fg = p.gold })
  hi("CmpItemKindTypeParameter", { fg = p.mag_bright })
  hi("CmpItemKindOperator",     { fg = p.fg_dim })
  hi("CmpItemKindReference",    { fg = p.cyan_br })

  -- ── Lazy ──────────────────────────────────────────────────
  hi("LazyNormal",              { fg = p.fg, bg = p.bg })
  hi("LazyButton",              { fg = p.fg, bg = p.surface })
  hi("LazyButtonActive",        { fg = p.bg_dark, bg = p.amber, bold = true })
  hi("LazyH1",                  { fg = p.bg_dark, bg = p.amber, bold = true })
  hi("LazyH2",                  { fg = p.gold, bold = true })
  hi("LazySpecial",             { fg = p.amber })
  hi("LazyProgressDone",        { fg = p.amber })
  hi("LazyProgressTodo",        { fg = p.overlay })

  -- ── Mini ──────────────────────────────────────────────────
  hi("MiniStatuslineFilename",  { fg = p.fg_dim, bg = p.bg_light })
  hi("MiniStatuslineDevinfo",   { fg = p.fg, bg = p.surface })
  hi("MiniStatuslineModeNormal", { fg = p.bg_dark, bg = p.amber, bold = true })
  hi("MiniStatuslineModeInsert", { fg = p.bg_dark, bg = p.teal, bold = true })
  hi("MiniStatuslineModeVisual", { fg = p.bg_dark, bg = p.mag_bright, bold = true })
  hi("MiniStatuslineModeReplace", { fg = p.bg_dark, bg = p.red_bright, bold = true })
  hi("MiniStatuslineModeCommand", { fg = p.bg_dark, bg = p.gold, bold = true })
  hi("MiniCursorword",          { bg = p.surface })
  hi("MiniCursorwordCurrent",   { bg = p.surface })

  -- ── Misc ──────────────────────────────────────────────────
  hi("healthSuccess",           { fg = p.bg_dark, bg = p.teal })
  hi("healthWarning",           { fg = p.bg_dark, bg = p.gold })
  hi("healthError",             { fg = p.bg_dark, bg = p.red_bright })
  hi("LspInfoBorder",           { fg = p.amber, bg = p.bg_light })
  hi("LspReferenceText",        { bg = p.surface })
  hi("LspReferenceRead",        { bg = p.surface })
  hi("LspReferenceWrite",       { bg = p.surface })
  hi("LspSignatureActiveParameter", { fg = p.gold, underline = true })
end

return M
